1. (pwd)
2. (ls -a)
3. (mkdir)
4. (touch )
5. (cp dosya adi ./klasor adi)
6. (Cd klasor adi )
7. ( rm dosya adi)
8. (echo "Yazi olan kisim" >> klosor adi )
9. (cat dosya adi )
10. (grep shell dosya adi)
11. (echo "Yazi olan kisim" >> klosor adi )
12. (cat dosyaadi dosyaadi >> olusturulacak dosya adi )
13. >> (cd ..)
14. (rm -r klasor adi)
15. (sudo su)